2018-11-10 18:06:56,135 ERROR: Exception on /user/ [GET] [in D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\GitHub\mycode\recruitment\app\main\user\views.py", line 27, in user_index
    title='用户列表', next_url=next_url, prev_url=prev_url)
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "E:\GitHub\mycode\recruitment\app\templates\main\user\index.html", line 2, in top-level template code
    {% import "_macros.html" as macros %}
  File "E:\GitHub\mycode\recruitment\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "E:\GitHub\mycode\recruitment\app\templates\base.html", line 73, in block "content"
    {% block app_content %}{% endblock %}
  File "E:\GitHub\mycode\recruitment\app\templates\main\user\index.html", line 20, in block "app_content"
    <a href="{{ url_for('main.user_edit', id=user.id) }}">{{ user.name }}</a>
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.user_edit' with values ['id']. Did you forget to specify values ['page']?
2018-11-10 18:07:18,411 ERROR: Exception on /user/ [GET] [in D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\GitHub\mycode\recruitment\app\main\user\views.py", line 27, in user_index
    title='用户列表', next_url=next_url, prev_url=prev_url)
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "E:\GitHub\mycode\recruitment\app\templates\main\user\index.html", line 2, in top-level template code
    {% import "_macros.html" as macros %}
  File "E:\GitHub\mycode\recruitment\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "E:\GitHub\mycode\recruitment\app\templates\base.html", line 73, in block "content"
    {% block app_content %}{% endblock %}
  File "E:\GitHub\mycode\recruitment\app\templates\main\user\index.html", line 20, in block "app_content"
    <a href="{{ url_for('main.user_edit', id=user.id) }}">{{ user.name }}</a>
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.user_edit' with values ['id']. Did you forget to specify values ['page']?
2018-11-10 18:07:32,144 INFO: 公司后台 startup [in E:\GitHub\mycode\recruitment\app\__init__.py:85]
2018-11-10 18:11:18,258 INFO: 公司后台 startup [in E:\GitHub\mycode\recruitment\app\__init__.py:85]
2018-11-10 18:17:16,823 INFO: 公司后台 startup [in E:\GitHub\mycode\recruitment\app\__init__.py:85]
